//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALNUBEV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMonthEndErrorLog
    {
        public long Id { get; set; }
        public Nullable<decimal> Member_Code { get; set; }
        public Nullable<int> YY { get; set; }
        public Nullable<int> MM { get; set; }
        public string ErrorMsg { get; set; }
    }
}
