//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALNUBEV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUBEBankBranch
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserCode { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string PostalCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string EMailId { get; set; }
        public Nullable<int> NUBEBankId { get; set; }
        public Nullable<int> NUBEBranchId { get; set; }
        public string V2Code { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsMerged { get; set; }
        public Nullable<bool> IsHeadQuarters { get; set; }
    
        public virtual NUBEBank NUBEBank { get; set; }
        public virtual NUBEBranch NUBEBranch { get; set; }
    }
}
