//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALNUBEV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUBEMembershipResignation
    {
        public int Id { get; set; }
        public Nullable<int> NUBEMembershipId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> NUBERelationId { get; set; }
        public Nullable<int> NUBEResignationReasonId { get; set; }
        public string ClaimerName { get; set; }
        public Nullable<int> ContributedMonth { get; set; }
        public Nullable<decimal> AccBF { get; set; }
        public Nullable<decimal> AccBenefit { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> TotalArrear { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> ServiceYear { get; set; }
        public string PayMode { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<decimal> UnionContribution { get; set; }
    
        public virtual NUBEMembership NUBEMembership { get; set; }
        public virtual NUBERelation NUBERelation { get; set; }
        public virtual NUBEResignationReason NUBEResignationReason { get; set; }
    }
}
