//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALNUBEV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUBEGender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NUBEGender()
        {
            this.NUBEMembershipNominees = new HashSet<NUBEMembershipNominee>();
            this.NUBEMembershipGuardians = new HashSet<NUBEMembershipGuardian>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserCode { get; set; }
        public int CompanyId { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NUBEMembershipNominee> NUBEMembershipNominees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NUBEMembershipGuardian> NUBEMembershipGuardians { get; set; }
    }
}
