//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALNUBEV3
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUBERace
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserCode { get; set; }
        public int CompanyId { get; set; }
        public string V2Code { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
    }
}
